# GitHub Sponsors
github: HowieDuhzit

# Buy Me a Coffee
buy_me_a_coffee: howieduhzit

# Ko-fi (if you have one)
# ko_fi: your_username

# Custom funding links
custom: ["https://www.buymeacoffee.com/howieduhzit", "https://app.warp.dev/referral/3E9X3D"]
