github: HowieDuhzit
buy_me_a_coffee: howieduhzit
solana: HowieDuhzit.sol
patreon: HowieDuhzit
open_collective: HowieDuhzit
ko_fi: HowieDuhzit
tidelift: HowieDuhzit
community_bridge: HowieDuhzit
liberapay: HowieDuhzit
issuehunt: HowieDuhzit
otechie: HowieDuhzit