# =============================================================================
# GitHub Sponsors - Has custom GitHub icon in funding section
# =============================================================================
github: HowieDuhzit

# =============================================================================
# Buy Me a Coffee - Has custom coffee cup icon in funding section
# =============================================================================
buy_me_a_coffee: howieduhzit

# =============================================================================
# Solana - Has custom Solana icon in funding section
# =============================================================================
solana: HowieDuhzit.sol

# Patreon - Has custom Patreon icon
patreon: HowieDuhzit

# Open Collective - Has custom Open Collective icon
open_collective: HowieDuhzit

# Ko-fi - Has custom Ko-fi icon
ko_fi: HowieDuhzit

# Tidelift - Has custom Tidelift icon
tidelift: HowieDuhzit

# Community Bridge - Has custom Community Bridge icon
community_bridge: HowieDuhzit

# Liberapay - Has custom Liberapay icon
liberapay: HowieDuhzit

# IssueHunt - Has custom IssueHunt icon
issuehunt: HowieDuhzit

# Otechie - Has custom Otechie icon
otechie: HowieDuhzit